### PR TITLE
feat: Add more flexible multi package support

### PR DESCRIPTION
**Pull request by jtdLab**
@Milad-Akarie 

Context: #1520

The feature can be tested in the example at https://github.com/jtdLab/auto_route_micro.

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
Hey @jtdLab Thank you for the great work, I'm sorry I haven't been responsive lately, I got a bit busy, I added some reviews.
in general I have the following notes: 
1-  I think it's better if we ditch the "micorRoutes" expression and stick to 'module'.
2- shouldn't the generated module implement an interface that has a pagesMap getter? 
3- Might need to revise the code building part as added a lot of changes. I haven't taken a good look at the code yet but right now I'm thinking a module is alot similar to a Router, I guess we only need to change what we extend and that's it?

**Comment by Milad-Akarie** [comment]
@jtdLab I meant something like this 
// routes.dart 
```dart
@AutoRouterConfig.module()
class MyPackageModule extends $MyPackageModule {}
```

// routes.module.dart
```dart
class $MyPackageModule extends _i2.AutoRouterModule {
  @override
  final Map<String, _i2.PageFactory> pagesMap = {
    SomeRoute.name: (routeData) {
      return _i2.AutoRoutePage<dynamic>(
        routeData: routeData,
        child: const _i1.SomePage(),
      );
    }
  };
}

as for no 3 I'll see how I can reduce changes to codebuilder

**Comment by jtdLab** [comment]
@Milad-Akarie i tried to cleanup the implementation a bit let me know if that fits.

**Comment by jtdLab** [comment]
> nice job, not sure if we need a third builder thu?

Yeah might be bit overkill.

> are we sure we don't want modules to have modules?

Im not sure it would offer more flexibility but also more nesting.

**Comment by Milad-Akarie** [comment]
@jtdLab I took a deeper look and I think it looks fine for now, a third builder might help guarantee that modules are generated before routers.

**Comment by jtdLab** [comment]
@Milad-Akarie 
When using `injectable` and `auto_route` in the same micro package they both have a `.module.dart` output which leads to:

```bash
[SEVERE] Conflicting outputs
  Both injectable_generator:injectable_config_builder and auto_route_generator:auto_router_module_generator may output lib/bootstrap.module.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```

This can be solved defining the `generate_for` of associated `injectable_generator:injectable_config_builder` and ` auto_route_generator:auto_router_module_generator` builders inside the `build.yaml` to only process the respective routes  and injection files. Maybe thats useful for other devs to know and worth a hint somewhere.

Would be something like:

```yaml
targets:
  $default:
    builders:
      auto_route_generator:auto_router_module_generator:
        generate_for:
          - path/to/router.dart
      injectable_generator:injectable_config_builder:
        generate_for:
          - path/to/injection.dart
```

**Comment by Milad-Akarie** [comment]
@jtdLab  I changed the output extension to .gm.dart   gm => (generated module), that should fix the issue.

**Pull request merged**
