### PR TITLE
Created option on router to toggle args generation

### LINKED ISSUE #510: Unhandled exception when push with argument
hi, i try to push some page with argument
```
await context.router.push(CameraPreviewPageRoute(
          path: path,
          isSubmit: (isSubmit) {
            if (isSubmit == true) {
              pickedData =
                  PickedData(path: path, takenDateTime: DateTime.now());
            }
          }));
```
and i'm get some exception ` Unhandled Exception: Expected [CameraPreviewPageRouteArgs],  found [CameraPreviewPageRouteArgs]`

```
T argsAs<T>({T Function()? orElse}) {
    final args = route.args;
    if (args == null) {
      if (orElse == null) {
        throw FlutterError(
            '${T.toString()} can not be null because it has a required parameter');
      } else {
        return orElse();
      }
    } else if (args is! T) {
      throw FlutterError(
          'Expected [${T.toString()}],  found [${args.runtimeType}]');
    } else {
      return args;
    }
  }
```
above the code, i think, args it's must be true with generic type, but why i get throw exception?

### PR DESCRIPTION
**Pull request by carlosfiori**
Fixes #510

### CODE REVIEW

**Comment by carlosfiori** [comment]
@Milad-Akarie

**Comment by carlosfiori** [comment]
@Milad-Akarie can you review?
I created this flag to have the ability to generate the args in a separated package, and export them

**Comment by carlosfiori** [comment]
@Milad-Akarie

**Comment by carlosfiori** [comment]
Just added some docs about this new flag in the README, @Milad-Akarie can you review?

**Comment by Milad-Akarie** [comment]
hey @carlosfiori  I'm really sorry for my late reply. 
 I don't understand how the router would work without the arguments. can you please explain it to me.

**Comment by carlosfiori** [comment]
Hi @Milad-Akarie, I just update this PR with latest master..
Was I able to explain the need for this functionality? Was there any doubt?

**Comment by carlosfiori** [comment]
@Milad-Akarie

**Comment by carlosfiori** [comment]
Hi @Milad-Akarie, could you review this please?

**Comment by pedromneto97** [comment]
Any update? @Milad-Akarie

**Comment by MateusAndradeGB** [comment]
Hi @Milad-Akarie, any updates on this ?

**Pull request closed without merging**
