### PR TITLE
Support for Complex function types for importing sources of the types

### PR DESCRIPTION
**Pull request by nateshmbhat**
### Related Issues : 
#97 

### Here's a sum up of the types that this PR adds support for : 
[x] Support generics or type parameterised functions
[x] Support named , optional , and positional parameters for function types
[x] Support importing return types for function types
[x] Support nested FunctionType ( `void Function(Function(int) , double)` ) parameters
[x] Support Future<FunctionType>
[x] Support type parameters that extend that some super class type . So import should happen for this super class :  ( `void Function<T extends TypeA>( int a, Type B)` )

### Some examples : 
+ TypeA Function(TypeB , TypeA , { TypeC typec , TypeD typed });
+ TypeA Function<T,List\<R>,S>(TypeB , TypeA , [ TypeC typec , TypeD typed ] );
+ final void Function<G extends TypeA>(LocationItem , CheckListItem , G subTypeOfTypeA ,{Future<CoreConfig> a , CreateOrderRequest b} ) onChanged;

**Function types inside Function type parameters** :

+ Future<TypeA> Function<T,List\<R>,S> (Function(TypeA , TypeB) , TypeC variable);
+ void Function<A,B,C,T,G extends TypeA ,F extends Function(TypeH)>(LocationItem , CheckListItem , T item , G subTypeOfTypeA , [int a , int b] ) onSelected;

## What I tested this on ? 

`final void Function<A,B extends NucleiNavigator ,C extends List<int> ,T,G extends BusService,F extends Function(GenericIconSelectionBar)>(LocationItem , CheckListItem , T item , G busService , [int a , int b] ) onSelected;`

`final void Function<G extends CommonService>(LocationItem , CheckListItem , G item ,{Future<CoreConfig> a , CreateOrderRequest b} ) onChanged;`

#### Generates following RouteArguments class : 

```dart
class BusBoardingDropScreenArguments {
  final Key key;
  final Int64 tripId;
  final PaginationRequest paginationRequest;
  final void Function<
          A,
          B extends NucleiNavigator,
          C extends List<int>,
          T,
          G extends BusService,
          F extends dynamic Function(GenericIconSelectionBar)>(
      LocationItem, CheckListItem, T, G,
      [int, int]) onSelected;
  final void Function<G extends CommonService>(LocationItem, CheckListItem, G,
      {Future<CoreConfig> a, CreateOrderRequest b}) onChanged;
  BusBoardingDropScreenArguments(
      {this.key,
      @required this.tripId,
      this.paginationRequest,
      @required this.onSelected,
      this.onChanged});
}
```

All the types have their corresponding source files imported correctly.

### CODE REVIEW

**Comment by nateshmbhat** [comment]
@Milad-Akarie can u review the PR once ?

**Comment by Milad-Akarie** [comment]
Hey @nateshmbhat I was really busy, sorry for the delay.

**Comment by Milad-Akarie** [comment]
@nateshmbhat nice job man. everything looks neats!

**Comment by nateshmbhat** [comment]
Thank you :) 
Looking forward to seeing the release on pub.dev

**Comment by Milad-Akarie** [comment]
@nateshmbhat already pushed to pup.dev

**Comment by nateshmbhat** [comment]
@Milad-Akarie you have updated only auto_route_generator it seems , but not `auto_route`. The changes also corresponded to the router classes in `auto_route` library also.

**Comment by Milad-Akarie** [comment]
My bad bro. I'm fasting lol 
I was saving 0.5.0 for the next build that's gonna include tests and some code refactoring. 
anyways everything is 0.5.0 now

**Comment by nateshmbhat** [comment]
Cool 👍

**Comment by seekcx** [comment]
Is the following format supported? I have an entity that doesn't seem to be imported and reports an error.

```dart 
final Future<SmsCaptchaEntity> Function() onSendCaptcha;
```

**Pull request merged**
