### PR TITLE
Update build.yaml

### PR DESCRIPTION
**Pull request by yang-lile**
`required_inputs: ['.g.dart']` will effect many package generation be changed to `.gr.dart` or disappear.
And all code don't use required_inputs to generation any other part. So I suppose remove this line, it can't work with hive package.

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
@yang-lile  this line is there so that auto_route generator runs after all generators outputting .g.dart files. it effects the execution order .

**Comment by yang-lile** [comment]
But I don't know how to work with both hive and auto_route.

same problem in this: https://github.com/hivedb/hive/issues/795

min project at: https://github.com/andye2004/hive_gen_works

**Comment by Milad-Akarie** [comment]
@yang-lile  you can use your own build.config files and controller the order using required_inputs and run_before
https://pub.dev/packages/build_config#adjusting-builder-ordering

**Comment by yang-lile** [comment]
sorry to disturb you, It is my code has problem.

**Comment by AntonLT** [comment]
@yang-lile Could you share, please, what was the issue?

**Pull request closed without merging**
