### PR TITLE
feat: deferred loading for web to enable code splitting for routes

### PR DESCRIPTION
**Pull request by Garzas**
Implemented solution for this issue https://github.com/Milad-Akarie/auto_route_library/issues/777

### CODE REVIEW

**Comment by itsbalamurali** [comment]
@Garzas any stats of performance? @ https://mydatamyconsent.com we use autoroute and this pr can help us.

**Comment by Garzas** [comment]
I can provide you a screenshot how size has changed
deferred
Currently I'm refactoring arguments between pages in my app, because to make it smaller all argument classes provided in `router.gr.dart` should only contain base classes, like `String` or `int`

**Comment by itsbalamurali** [comment]
@Garzas Thanks, once merged I can test and let you know the performance impact (We have a web app with 300+ complex routes and currently the `main.dart.js` file is about 70MB+ in size. @Milad-Akarie What are your thoughts on this?

**Comment by Garzas** [comment]
@itsbalamurali You can check only for testing purposes by adding these libraries to pubspec.yaml
`  auto_route:
    git:
      url: https://github.com/Garzas/auto_route_library.git
      path: auto_route
      ref: 47227dc7b9a8ed57fa6eaabaf8c21b6bd966e62a`
`  auto_route_generator:
    git:
      url: https://github.com/Garzas/auto_route_library.git
      path: auto_route_generator
      ref: 6d0d70acdc908991a70a707e5c77b29d7d47b036`

**Comment by itsAmitGoyani** [comment]
@Garzas This is Amit from @itsbalamurali's team. We've tried this library and it's not working for nested routes. Few nested imports are not marked as 'deferred'.

**Comment by Garzas** [comment]
@itsAmitGoyani thanks for feedback. I will try to fix this.

**Comment by Garzas** [comment]
@itsAmitGoyani fixed, updated previous libraries path

**Comment by jonasbark** [comment]
Hi @Garzas !
We ran into the following issue:
```
Error: Extension 'AutoRouterX' cannot be imported through a deferred import.
import 'package:auto_route/auto_route.dart' deferred as _i13;
^
lib/utils/router.gr.dart:58:21:
Error: The type 'Page<dynamic> Function(RouteData)' is deferred loaded via prefix '_i13' and can't be used as a type annotation.
 - 'Page' is from 'package:flutter/src/widgets/navigator.dart' ('../flutter/packages/flutter/lib/src/widgets/navigator.dart').
 - 'RouteData' is from 'package:auto_route/src/router/controller/routing_controller.dart'
 ('../flutter/.pub-cache/git/auto_route_library-0b8ad4fc4e9acd9872bdc298d01e27f616794a43/auto_route/lib/src/router/controller/routing_controller.dart').
  final Map<String, _i13.PageFactory> pagesMap = {
```

I added deferredLoading: true to the root annotation:
```
@CustomAutoRouter(
  transitionsBuilder: TransitionsBuilders.fadeIn,
  replaceInRouteName: 'Page,Route',
  deferredLoading: true,
  routes: <AutoRoute>[...
```
my guess is that it happens when we use EmptyRouterPage as page definition:
```
AutoRoute<dynamic>(path: '...', page: EmptyRouterPage, name: '...', children: [
...
          ]),
```

**Comment by Garzas** [comment]
@Milad-Akarie do you have any feedback?

**Comment by prem-banker** [comment]
@Garzas You are a live saver. It's working brilliantly. 

I faced an issue though. I use bloc for state management and use `wrappedRoute` method to wrap providers around my widgets. When I navigate to a widget with `wrappedRoute`, it can't find the provider context. Any idea how I could get around this?

Sample:
```dart
class SampleRoute extends StatefulWidget implements AutoRouteWrapper {

  @override
  _SampleRouteState createState() => _SampleRouteState();

  @override
  Widget wrappedRoute(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<Cubit1>(create: (context) => Cubit1()),
        BlocProvider<Cubit2>(create: (context) => Cubit2()),
      ],
      child: this,
    );
  }
}
```
This is a deferred route and when I navigate here, I get a Provider error saying: `This happens because you used a `BuildContext` that does not include the provider`

Good work on the deferred feature 👍

**Comment by Garzas** [comment]
@prem-banker have you tried it with StatelessWidget? If yes, I will try to resolve it after weekend

**Comment by prem-banker** [comment]
@Garzas Yo! It seems to work with stateless widgets but I sorta require stateful widgets for my project. 

PS: Thanks for the quick reply. Would love to use it with StatefulWidget as well

**Comment by Garzas** [comment]
I will handle it in next week, because I'm sick :/

**Comment by itsbalamurali** [comment]
> I will handle it in next week, because I'm sick :/

Sure, please take care <3!

**Comment by Garzas** [comment]
Updated fork
auto_route: git: url: https://github.com/Garzas/auto_route_library.git path: auto_route ref: ce447ad8ade265bb15a171e91bb62f7610daf850
auto_route_generator: git: url: https://github.com/Garzas/auto_route_library.git path: auto_route_generator ref: 5f75a49b2d342d3c7084de3f63c75d431ae49bc0

**Comment by prem-banker** [comment]
Hey @Milad-Akarie, any updates on the PR? With the new release of lib, this has become outdated and along with the release of Flutter 3, it's getting difficult to upgrade. How can I help?

**Comment by Garzas** [comment]
I've updated PR to the latest version now you can use it by tag to know when was the last update:
```  
auto_route:
    git:
      url: https://github.com/Garzas/auto_route_library.git
      path: auto_route
      ref: 4.0.1
auto_route_generator:
    git:
      url: https://github.com/Garzas/auto_route_library.git
      path: auto_route_generator
      ref: 4.0.1g

**Comment by Milad-Akarie** [comment]
@Garzas  is this ready now? last time I open the PR it said under development.

**Review by Milad-Akarie — COMMENTED** [review]
Were `EmptyRouterPage` and `EmptyRouterScreen` removed on propose? if so why?

**Comment by prem-banker** [comment]
Hey, @Garzas! Thanks for the update. I tried using the overrides with Flutter 3.0.0 but the generator wasn't outputting deferred routes. So, instead, I tried this and it worked:

```yaml
dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Garzas/auto_route_library.git
      path: auto_route
      ref: ab0b0f808cece74570bb150e8e9a8213ca443200
  auto_route_generator: 
    git: 
      url: https://github.com/Garzas/auto_route_library.git 
      path: auto_route_generator 
      ref: ab0b0f808cece74570bb150e8e9a8213ca443200
```

**Comment by cfregin** [comment]
> @Garzas You are a live saver. It's working brilliantly.
> 
> I faced an issue though. I use bloc for state management and use `wrappedRoute` method to wrap providers around my widgets. When I navigate to a widget with `wrappedRoute`, it can't find the provider context. Any idea how I could get around this?
> 
> Sample:
> 
> ```dart
> class SampleRoute extends StatefulWidget implements AutoRouteWrapper {
> 
>   @override
>   _SampleRouteState createState() => _SampleRouteState();
> 
>   @override
>   Widget wrappedRoute(BuildContext context) {
>     return MultiBlocProvider(
>       providers: [
>         BlocProvider<Cubit1>(create: (context) => Cubit1()),
>         BlocProvider<Cubit2>(create: (context) => Cubit2()),
>       ],
>       child: this,
>     );
>   }
> }
> ```
> 
> This is a deferred route and when I navigate here, I get a Provider error saying: `This happens because you used a `BuildContext` that does not include the provider`
> 
> Good work on the deferred feature 👍

I can't even build web when I use AutoRouteWrapper.

**Comment by cfregin** [comment]
@Garzas I would recommend to make the `deferredLoading`Flag optional in `AutoRoute`. And then use the Annotations `deferredLoading`Flag the default. Then you could activate deferred for all pages except the `AutoRoute(deferredLoading: false)` ones.

**Comment by cfregin** [comment]
> Were `EmptyRouterPage` and `EmptyRouterScreen` removed on propose? if so why?

Yes. I need them! :)

**Comment by Milad-Akarie** [comment]
@Garzas can we wrap this up?

**Comment by Garzas** [comment]
Hey @Milad-Akarie! I will get this updated tomorrow with @cfregin comments

**Comment by Milad-Akarie** [comment]
@Garzas Thank you very much, I'll look at this as soon as I can.

**Comment by Milad-Akarie** [comment]
@Garzas Wonderful work, works great, I have some points to discuss with you before we merge this into master.
1- Since deferred loading depends mainly on import syntax I guess we should lock the functionality when part-file approach is used.
2-  What's the point of the `deferredLoading` inside of `AutoRouterAnnotation`? is it to globally toggle deferred loading or is it a default value for other routes? I'm asking because I when I set a specific route as deferred while the global `deferredLoading` is null nothing happens. 
3- I believe we can make a generated file a bit cleaner by using a widget that wraps the FutureBuilder logic since it's  almost the same for every route, maybe something like the [DeferredWidget](https://github.com/flutter/gallery/blob/main/lib/deferred_widget.dart) from flutter gallery but less complicated.

**Comment by Garzas** [comment]
1. I agree, but can you explain me what are benefits of using this part-file approach? Should we remove this entirely?
2. I need to complete this functionality to set default deferred loading for all routes and then control them separately in single route (I need to fix some passing variables and force to make deferred children if parent is deferred)
3. I totally agree! I will make improvements, thanks!

**Comment by ugurberkecan** [comment]
> 

Could you share some implementations examples?

**Comment by Milad-Akarie** [comment]
@Garzas Some users asked for the part-file approach, we could simply add a generate-time assertion that explains why this feature can not work with part-file approach.

**Comment by cacianokroth** [comment]
Has something prevision for release version?

Regards

**Comment by Garzas** [comment]
Hey, @Milad-Akarie! Can you take a look on latest changes?

**Comment by Garzas** [comment]
> > 
> 
> Could you share some implementation examples? Especially how can we add this in the materialautorouter ?

@ugurberkecan I will prepare another PR with examples after merging this PR 😄

**Comment by Milad-Akarie** [comment]
@Garzas Impressive work, All the points from previous discussion has been handled. 
I have two more tiny points thu, I can do them by my self but I would like you to know what's going on. 
first I can't get read of these two shipped widgets `EmptyRouterPage` and `EmptyRouterScreen` I heavily use them my self. we could export them both in a separate file like `auto_route_common.dart` for example so there is no Deferred import issues. 

Secondly we have to handle the case where two or more routes are using the same Deferred widget but it's only marked Deferred in one of them. 

in the following example I've marked BooksRoute as deferred but ProfileTab is also using the same widget.

   ```dart
 BooksTab.name: (routeData) {
      return _i13.MaterialPageX<dynamic>(
          routeData: routeData,
          child: _i13.DeferredWidget(
              _i4.loadLibrary, () => _i4.EmptyRouterPage()));
    },
    ProfileTab.name: (routeData) {
      return _i13.MaterialPageX<dynamic>(
          routeData: routeData, child: const _i4.EmptyRouterPage()); // this complains that const can not be used with deferred import
    },

```
I guess the solution here is to make other routes that use a deferred widget deferred as well regardless if whether they're marked deferred.
What are you thoughts?

**Comment by Garzas** [comment]
@Milad-Akarie good catch! I think we can revert removing `EmptyRouterPage` just make sure that it will not depend on any deferred imports. You are the autor of that lib so I think you will make those improvements faster 💪 
Just one suggestion: can you make PR with those changes to my PR. It will help me understand where have you resolved those issues? 🙏 

Thanks for feedback!

**Comment by Milad-Akarie** [comment]
@Garzas I'm trying to fork your fork but it says I already got the fork, not sure if I'm doing something wrong or if it's not supposed to work this way. 
Can you resolve the conflicts with latest merge so I can work on directly?

**Comment by Garzas** [comment]
done

**Comment by ugurberkecan** [comment]
> > Could you share some implementation examples? Especially how can we add this in the materialautorouter ?
> 
> @ugurberkecan I will prepare another PR with examples after merging this PR 😄

Nice work after all, I am waiting your new PR :)

**Comment by slavap** [comment]
@Garzas @Milad-Akarie 
deferredLoading and AutoRouteWrapper are not working together, see https://github.com/Milad-Akarie/auto_route_library/issues/777#issuecomment-1220221342

**Comment by Milad-Akarie** [comment]
@slavap should be fixed in current build, Thanks for reporting

**Comment by ugurberkecan** [comment]
Hi @Milad-Akarie, could you add more information in document about how can we activate it ?

**Comment by slavap** [comment]
@ugurberkecan 
You can activate it for all routes:
```dart
@MaterialAutoRouter(deferredLoading: true,
```
or per particular routes:
```dart
CustomRoute(deferredLoading: true,
```

**Comment by ugurberkecan** [comment]
Hi thank you first but I tried it but there is no changes about loading time and size. Do you get any improvements ? @slavap

**Comment by dreamchrome** [comment]
Is there a way to have a loading indicator while it is performing the deferred loading?

This feature seriously saved my client's web app on slow connections. If it could have some loading indicator instead of a white blank screen when changing pages, it would be amazing.

**Comment by slavap** [comment]
@dreamchrome 
Have you tried to use RouteObserver ?
```dart
MaterialApp.router(routerDelegate: AppRouter().delegate(navigatorObservers: () => [appRouteObserver]),
```
So didPop() and didPush() will be called when routes are about to change and you can initiate loading indicator there?

**Pull request merged**
