### PR TITLE
Fixed back gesture when nested navigator only has one entry

### PR DESCRIPTION
**Pull request by iagoandrei**
Fix: https://github.com/Milad-Akarie/auto_route_library/issues/1938

### CODE REVIEW

**Comment by iagoandrei** [comment]
@Milad-Akarie I believe this fixes the indicated issue. Please review

**Comment by iagoandrei** [comment]
Now it's really ready

**Comment by Milad-Akarie** [comment]
@iagoandrei now it makes more sense, thanks for your efforts

**Comment by ziqq** [comment]
#### Not fixed

imageimage

**Pull request merged**
