### PR TITLE
add *.gr.dart to gitignore

### PR DESCRIPTION
**Pull request by benyaminbeyzaie**
I think this file is making repo so dirty on commits and should be ignored and generated every time.
this would be helpful if you can add it to the docs

### CODE REVIEW

**Comment by foxanna** [comment]
The `.gr.dart` file is already in the repo. If the goal of this PR is to stop committing generated files, not only they should be ignored, but also existing files should be removed. Otherwise, the generated `.gr.dart` file will just sit there and age, while the `.dart` counterpart may be updated with the new configuration.
But overall, generated files better be kept in the repo. This way the code is always in a compilable state.

**Comment by benyaminbeyzaie** [comment]
You are right! I'm closing this PR and will open another later on this topic, But I'm disagree about keeping generated files in the repo. For example in our team every time one of the team members change something in the routes they should commit and push whole generated files again and with some small changes they should commit a large amount of code. also they should resolve conflicts in the generated files(I think best way to resolve the conflicts in generated files is to remove them and generate them again). with those arguments above our solution in the team was to remove the `.gr.dart` files from the repo and generate them in our local code. managing repo after that change is lot easier...

**Comment by foxanna** [comment]
Well, team members have this opportunity to make only small changes because code generation does all the heavy lifting for writing the boilerplate code. Still, generated changes are a part of the changes your colleagues are doing.
I understand the pain of resolving conflicts in generated files. You are right, regenerating them is the easiest way.
However, committing or not generated files also depends on the size of the team and the project. In projects with tens and hundreds of packages, code generation takes tens of minutes. Every time a team member has to pull `main`, if generated files are not committed, they have to run code generation in the entire project locally to ensure their local generated files are up to date with the updated configuration. With engineers doing this multiple times a day, keeping generated code in the repo is a huge time saver.

**Comment by benyaminbeyzaie** [comment]
You are absolutely right about the size of the generated codes and that should be a matter of concern too. I guess for the routing system size of the generated codes will not be that much but of course as you said making decision about keeping the generated codes in the repo should be made based on developers experience in the team and generated files size.

**Pull request closed without merging**
