### PR TITLE
Adds pageView factory constructor to AutoTabsRouter

### PR DESCRIPTION
**Pull request by Nolence**
Deleted my old PR as I really didn't think I was doing it right. This new PR should be non-breaking as the default constructor is replaced with a default factory constructor.

This should handle #311

Let me know if you need any changes :)

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
Hey @Nolence I just got a chance to look at this PR, Thank you so much. 
The biggest issue I faced with the TabsRouter is keep the state of children, a PageView disposes it's offstage children state which causes the Nested Routers to rebuild and that's causing a lot of issues, you could see it in the logs.

my second point is that I think the PageView better be built-in inside of AutoTabsRouter to avoid confusion + to get things going with lesser code, what do you think?

**Comment by Nolence** [comment]
Hi, yeah I hadn't thought of the children disposal nor did I see it immediately but I'll look into possible solutions.

The second point about pageview being inside AutoTabsRouter I'll have to look into to just see what feels more natural. If it turns out that we need to move inside anyways to avoid the children disposal issue than that'd likely be best. However because PageView has several constructors for different use cases (`.builder`, `.custom`) as well as a lot of configuration, we'll have to think if the trade off is better in terms of user experience versus customizability.

**Comment by SalahAdDin** [comment]
Is it possible to use the `TabsRouter` with PageView?

**Comment by bounty1342** [comment]
"PageView disposes it's offstage children", if they are not setup with keep Alive correctly, otherwise, it should be fine.

**Comment by ariefwijaya** [comment]
+1 , please follow up this PR

**Comment by Milad-Akarie** [comment]
@Nolence  is this ready?

**Comment by Nolence** [comment]
No, revisited this morning actually and I couldn't get the environment to run. Getting missing pub deps or mismatched stuff.

I don't mind closing and letting someone else takeover. Sorry, just haven't had the time to actually dig into this with my new job.

On a side note, I recently started using [melos](https://melos.invertase.dev/) for my own multi package repos and it's really cool. Highly recommend as it will locally link your packages but you can still have remote dep versions.

**Comment by Nolence** [comment]
Yeah, I'm gonna close and let someone else take the lead as this does seem like something a lot of people want and I don't want to get in the way of that.

**Pull request closed without merging**
