### PR TITLE
Fix AutoRouteConfig.module() doesn't generate part of file correctly.

### PR DESCRIPTION
**Pull request by JimmyTai**
- [x] Use `generateExtension` to replace file name in `_hasPartDirective` method.

related to #1624

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
Thanks @JimmyTai

**Comment by JimmyTai** [comment]
@Milad-Akarie  Could you help to arrange a release for this bug fix. Or you wanna wait for other PRs?

**Comment by Milad-Akarie** [comment]
@JimmyTai totally missed this, I forgot that this pr effect auto_route_generator and only published a new auto_route release.

**Comment by Milad-Akarie** [comment]
@JimmyTai published

**Comment by JimmyTai** [comment]
> @JimmyTai published

Thanks a lot.

**Pull request merged**
