### PR TITLE
feat: add back mixin to AutoRouteAware

### LINKED ISSUE #1734: AutoRouteAware can no longer be used as a mixin
My main issue is not being able to use `AutoRouteAware` as a mixin because I'm trying to use it with `flutter_hooks` and because I need to extend `HookState`, I can't extend `AutoRouteAware` and I don't want to `implement` it either because I don't need all of the methods.

### PR DESCRIPTION
**Pull request by Reprevise**
Fixes #1734 

Dart 3 restricted the use of the `with` keyword for classes declared as `mixin class` or `mixin`. This PR changes AutoRouteAware from `abstract class AutoRouteAware` to `abstract mixin class AutoRouteAware`.

### CODE REVIEW

**Comment by AAverin** [comment]
@Reprevise did this resolve the issue for you? I also need to use AutoRouteAware with flutter_hooks.
@Milad-Akarie it's a super-tiny PR and would be great to have it merged if doesn't break anything in the library

**Comment by Reprevise** [comment]
Hey @AAverin!

It did work for me. For now, you can use my branch in your pubspec.yaml like so:

```yaml
auto_route:
  git:
    url: https://github.com/Reprevise/auto_route_library.git
    path: auto_route
    ref: bb2c0470d3a82e65b9f5515e1f46515bdbcfea3c
```

**Comment by Reprevise** [comment]
@Milad-Akarie It doesn't appear like these changes made it into the package, can you check?

**Comment by Milad-Akarie** [comment]
@Reprevise No idea how that slipped, I merged a couple of PRs that day something must've gone wrong. 
anyways fixed in 7.9.1

**Pull request merged**
