### PR TITLE
test setup

### LINKED ISSUE #614: auto_route_generator test
Hi @Milad-Akarie 

I'm actively maintaining `Atremis` code generator.
I noticed that you do not have any tests for `auto_route` generator.

We have som https://github.com/comigor/artemis/tree/master/test

Are you interested in adding test?
If yes - I can try to start adding them...

### PR DESCRIPTION
**Pull request by vasilich6107**
Fix #614 

Hi @Milad-Akarie 
This is test setup approach that I was recommended to follow while writing my own generator package.
You can read a thread here https://github.com/artflutter/reactive_forms_generator/pull/1

The valuable part from the thread
```
Well, using TypeChecker.fromUrl() you don't need a 
compile time dependency, which is what prevented 
the builder from working since it transitively pulled in Flutter.
The reactive_forms_generator simply has no dependency 
on reactive_forms_annotations or reactive_forms. 
It will just fail to build if the dependency is not added 
at runtime. So this may also be a small downside. 
But a lot of Flutter generators work this way.
```

Run tests with `dart test` command

### CODE REVIEW

**Comment by Milad-Akarie** [comment]
@vasilich6107  any other downsides for using TypeChecker.fromUrl()?

**Comment by vasilich6107** [comment]
No actually)
You can check - i wrote pretty large package
https://github.com/artflutter/reactive_forms_generator

**Comment by vasilich6107** [comment]
Oh)
I just wanted to mention that for now I did not found a way to run tests in debugger with IDE for `dart test` command
Frankly speaking I did no spent too much time to investigate...

**Comment by Milad-Akarie** [comment]
@vasilich6107 the test looks good, it passed, I tried changing the output file and it caught it. 
I'm ready to merge this if you are? or are you planning to add more tests first? 
also I think `AutoTabsScaffold` wasn't updated yet?

**Comment by vasilich6107** [comment]
Hi @Milad-Akarie 

I’m ready to merge. This is initial setup so small test is enough to start.
I would like to kindly ask you to setup PR checks after merging tests setup.

I didn’t get your question about AutoTabsScaffold. Could you add more details there?

I will be on vacation next week. So I will add more tests after. Technically I’m planning to add and docs based on tests to cover more the functionality of the library

**Comment by vasilich6107** [comment]
@Milad-Akarie could we merge this PR?

**Comment by Milad-Akarie** [comment]
@vasilich6107 I'm really sorry for the delay, I got really busy.

**Pull request merged**
