### PR TITLE
PageRouteInfo<void>

### LINKED ISSUE #612: Generated file is not `strong-mode` compliant
Hi. Thanks for you work. I'm using `strong-mode` in my project.
While generating file the result is not `strong-mode` compliant.

```yaml
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

For example it generates code like

```dart
class DeniedScreenRoute extends _i1.PageRouteInfo {
  const DeniedScreenRoute() : super(name, path: '/denied-screen');

  static const String name = 'DeniedScreenRoute';
}
```

Which gives an error 

```
error: Missing type arguments for generic type 'PageRouteInfo<dynamic>'. (implicit_dynamic_type at [vesselitineraryapp] lib/routes/router.gr.dart:116)
```

image

### PR DESCRIPTION
**Pull request by vasilich6107**
Fix #612

### CODE REVIEW

**Comment by vasilich6107** [comment]
Hi @Milad-Akarie added a tiny PR.

**Comment by vasilich6107** [comment]
@Milad-Akarie - fixed conflicts

**Comment by vasilich6107** [comment]
Thanks a lot for merging

**Comment by Milad-Akarie** [comment]
@vasilich6107 Thank you for your efforts.

**Pull request merged**
